### ISSUE TITLE
Support for converting between formats

### ISSUE THREAD

**Issue by XaeroDegreaz** [Gagravarr/VorbisJava#20]
Well first, I'd like to congratulate you on being the only framework that I've found that's actually able to open and read the .spx file I've been given to test with.

Looking through your tests, I haven't ran across anything that would allow me to convert to another format. Is that something you have planned for a future release?

I really need to be able to retrieve and convert .spx files to something more readily readable by end-users.

Thanks in advance.

**Comment by Gagravarr** [comment]
My interests largely just run to "whatever Apache Tika needs" and "whatever makes managing my own audio collections easier". I'd really love to have some Audio decoding support, but it's not something I've planned to spend any free time working on

At a rough guess, you're looking at person-days rather than person-hours of work to add audio decoding support, but probably not person-weeks....

**Comment by XaeroDegreaz** [comment]
I can understand that. Thanks for the response :)
