### ISSUE TITLE
Javadoc generation causes build failure

### ISSUE THREAD

**Issue by mondain** [Gagravarr/VorbisJava#38]
I had to use `-Dmaven.javadoc.skip=true` on the command line to build, I suggest turning off the doc dependency for a build or fixing the errant items; I may do a PR if I get a chance to save you the time.

**Comment by nick-burch-flec** [comment]
I'm not getting any javadoc related errors building on my system - what version of the JDK / JavaDoc tool are you seeing this on, and what's the error?

**Comment by mondain** [comment]
@nick-burch-flec I'm using AWS Corretto JDK 8 and Maven 3.6.0; you will find the terminal output of `mvn clean package` here: https://pastebin.com/Bc8pWPQ8

**Comment by nick-burch-flec** [comment]
It seems javadoc has got stricter from Java 8-ish onwards. Not sure how it's fine for my JDK8 though! A few suggestions for turning off the warnings at https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete , can you see if you can find one of those that works, since I can't reproduce?

(Fixing the javadocs on methods seems the slower option!)

**Comment by mondain** [comment]
Yeah, much stricter, but I'm really loving the work Amazon is doing for the OpenJDK (not saying its them specifically when generating the docs). I've got no problem fixing the javadoc tags and doing a PR this weekend time permitting of course. Skipping javadoc is the easiest way to get past this for today.

**Comment by mondain** [comment]
Not trying to crosspost here, but do you have any idea what I'm doing wrong for issue https://github.com/Gagravarr/VorbisJava/issues/39 ?
